services:
  admin:
    build:
      context: .
      args:
        NEXT_PUBLIC_IAM_API: https://iam.smana.web.id/v1
    container_name: admin
    restart: unless-stopped
    ports:
      - "3000"
  
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: admin_cloudflared
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    depends_on:
      - admin